feat(boards): #MAG-5/6 (back) display+create all boards
CGI-OPEN-ENT-NG/magneto pull request #1
Opened 2022-09-12 15:13 UTC by flmartineau

## Describe your changes

- Added 2 API endpoints for creating a board and fetching all boards

## Checklist tests

- check if both APIs are behaving properly with the expected parameters (see : https://confluence.support-ent.fr/display/RN/Boards)

## Issue ticket number and link

https://jira.support-ent.fr/browse/MAG-5
https://jira.support-ent.fr/browse/MAG-6

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2022-09-13 07:21 UTC, lapeyronnie commented on src/main/java/fr/cgi/magneto/controller/BoardController.java
> +                                    log.error(err.getMessage());
tu pourrais ajouter la classe dans le message d'erreur comme tu l'as fait pour laclasse DataHelper.

2022-09-13 10:03 UTC, JinDouang requested changes

2022-09-13 10:03 UTC, JinDouang commented on src/test/java/fr/cgi/magneto/model/BoardTest.java
> +    public void testCourseHasContentWithObject(TestContext ctx) {
"course"

2022-09-13 10:03 UTC, JinDouang commented on src/test/java/fr/cgi/magneto/model/MongoQueryTest.java
> +        ctx.assertEquals(mongoQueryObject_1, mongoQuery.getAggregate());
pour compare ton json et ce qu'on s'attend vraiment ici!

2022-09-13 12:15 UTC, flmartineau commented on src/main/java/fr/cgi/magneto/service/impl/DefaultBoardService.java
> +        //TODO: fetch shared boards (MAG-16)
oui je le précise en commentaire car pour l'instant le paramètre `sortBy` n'est pas utilisé

2022-09-14 08:05 UTC, JinDouang approved these changes

2022-09-14 10:01 UTC, qpic-cgi commented on src/main/java/fr/cgi/magneto/controller/BoardController.java
> +                        log.error(message);
tu gères déjà ton erreur dans ta méthode, tu ne risques pas d'avoir un spam de logs ?

2022-09-14 10:01 UTC, qpic-cgi commented on src/main/java/fr/cgi/magneto/controller/BoardController.java
> +                                    log.error(message);
cf https://github.com/CGI-OPEN-ENT-NG/magneto/pull/1/files#r970592943

2022-09-14 10:15 UTC, qpic-cgi commented on src/main/java/fr/cgi/magneto/model/MongoQuery.java
> +public class MongoQuery {
Dans statistics-presences on utilise l'object AggregationsBuilder pour construire les requêtes mongo, c'est relativement pratique !
https://github.com/OPEN-ENT-NG/presences/blob/1601004f41e7bacf57874175075d6139e81d3e77/statistics-presences/src/main/java/fr/openent/statistics_presences/bean/weekly/WeeklySearch.java#L38

2022-09-14 10:19 UTC, qpic-cgi requested changes

2022-09-14 10:19 UTC, qpic-cgi commented on src/main/java/fr/cgi/magneto/model/MongoQuery.java
> +public class MongoQuery {
Dans statistics-presences on utilise l'object AggregationsBuilder pour construire les requêtes mongo, c'est relativement pratique !
https://github.com/OPEN-ENT-NG/presences/blob/1601004f41e7bacf57874175075d6139e81d3e77/statistics-presences/src/main/java/fr/openent/statistics_presences/bean/weekly/WeeklySearch.java#L38

2022-09-15 10:38 UTC, merged