feat(boards): #MAG-5/6 (front) add boards view + create popup
CGI-OPEN-ENT-NG/magneto pull request #2
Opened 2022-09-19 09:43 UTC by flmartineau

## Describe your changes

- add boards view
- add board creation popup 

## Checklist tests

- test if board creation is functionning properly
- test that the board list if correctly displayed

## Issue ticket number and link

https://jira.support-ent.fr/browse/MAG-5
https://jira.support-ent.fr/browse/MAG-6

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2022-09-19 09:51 UTC, BastienBenard commented on src/main/resources/public/template/boards.html
> +            <div class="list-header row"><!--TODO dans directive -->
Ce sera fait dans un future ticket ?

2022-09-19 10:29 UTC, sjollois approved these changes

2022-09-19 11:56 UTC, BastienBenard commented on src/main/resources/public/ts/directives/board-list/board-list.directive.ts
> +    boards: Array<IBoard>;
Tu dois le déclaré ici ? Tu la pas déjà grâce a IBoardListProps ? (this.$scope.vm.boards)

2022-09-19 12:24 UTC, BastienBenard commented on src/main/resources/public/ts/directives/board-search-bar/board-search-bar.directive.ts
> +    //searchText: string;
c'est utile de le grader

2022-09-19 12:28 UTC, BastienBenard commented on src/main/resources/public/ts/directives/board-search-bar/board-search-bar.directive.ts
> +    searchText: string;
si ton IVewModel implement tes props, tu n'as plus besoin de déclarer tes variables

2022-09-19 12:28 UTC, BastienBenard commented on src/main/resources/public/ts/directives/board-search-bar/board-search-bar.directive.ts
> +        link: function (scope: ng.IScope,
typage scope => IBoardSearchBarScope

2022-09-19 12:33 UTC, BastienBenard commented on src/main/resources/public/ts/directives/board-search-bar/board-search-bar.directive.ts
> +class Controller implements ng.IController, IViewModel {
Plus besion de ng.IController si tu type IViewModel en ng.IController

2022-09-19 12:43 UTC, flmartineau commented on src/main/resources/public/template/boards.html
> +<!--                    </div>-->
oui les filtres seront ajoutés plus tard du coup j'ai gardé mais en commentaires

2022-09-19 12:45 UTC, flmartineau commented on src/main/resources/public/template/boards.html
> +            <div class="list-header row"><!--TODO dans directive -->
J'ai oublié d'enlever le commentaire, la directive était prévue pour les filtres mais comme on en a pas besoin pour le moment le commentaire sert à rien

2022-09-19 13:38 UTC, BastienBenard approved these changes

2022-09-19 15:01 UTC, JinDouang requested changes

2022-09-19 15:01 UTC, JinDouang commented on src/main/resources/public/ts/magnetoBehaviours.ts
> +    boardCategoriesService: new BoardCategoriesService,
Il ne faudrait pas tout déclarer dans le behaviours...

2022-09-19 15:01 UTC, JinDouang commented on src/main/resources/public/ts/services/boards.service.ts
> +                return res.data;
Avec un vrai model

2022-09-21 08:19 UTC, JinDouang requested changes

2022-09-21 10:02 UTC, JinDouang approved these changes

2022-09-21 10:22 UTC, merged