feat(cards): #MAG-50 add cards collection
CGI-OPEN-ENT-NG/magneto pull request #20
Opened 2022-11-02 15:15 UTC by Sofianebernoussi

## Describe your changes

- add a publish board lightbox
- allow users to open any public board in read-only
- add tags to boards and allow searching on tags

Updated API doc : https://confluence.support-ent.fr/display/RN/Boards

## Checklist tests

- check if duplication is working
- check if the card collection is correctly displayed

## Issue ticket number and link

https://jira.support-ent.fr/browse/MAG-50

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [X] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [X] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2022-11-02 15:47 UTC, flmartineau commented on src/main/java/fr/cgi/magneto/controller/CardController.java
> +                .onSuccess(result -> renderJson(request, result.get(0).toJson()))
Ajoute une vérif sur le result avant le .get(0)

2022-11-02 16:06 UTC, flmartineau commented on src/main/resources/public/ts/directives/infinite-scroll.directive.ts
> +    querySelector: string;
Tu peux l'enlever, il est défini dans les props

2022-11-02 16:47 UTC, Sofianebernoussi commented on src/main/resources/public/ts/directives/card-list/card-list-item-options.directive.ts
> +                element.click(function (event) {
nop il reconnait pas le mousevent du coup je me tape un undefined

2022-11-03 10:12 UTC, qpic-cgi requested changes

2022-11-03 10:12 UTC, qpic-cgi commented on src/main/resources/public/ts/directives/card-collection/card-collection.directive.ts
> +        controller: ['$scope', '$location', '$window', '$parse', Controller],
Ici, tu ne te sers ni du $location, ni du $window, ni du $parse.
Adapte ton constructeur aussi !

2022-11-03 10:12 UTC, qpic-cgi commented on src/main/resources/public/ts/directives/card-collection/card-collection.directive.ts
> +            vm.submitDuplicate = async (card?: Card): Promise<void> => {
Pourquoi tu déclare cette méthode ici ?

2022-11-03 10:12 UTC, qpic-cgi commented on src/main/resources/public/ts/directives/card-navbar/navbar-item/navbar-item.directive.ts
> +                private $window: IWindowService) {
tu ne te sers pas de ton $location, ni de ton $window

2022-11-03 10:12 UTC, qpic-cgi commented on src/main/resources/public/ts/directives/card-preview-lightbox/card-preview-lightbox.directive.ts
> +                private $window: IWindowService) {
tu ne te sers pas de ton $location, ni de ton $window

2022-11-03 10:12 UTC, qpic-cgi commented on src/main/resources/public/ts/directives/infinite-scroll.directive.ts
> +            });
tu devrais pouvoir rendre générique la partie :
.on("scroll", async () => {
     await vm.scroll();
});

2022-11-03 10:18 UTC, Sofianebernoussi commented on src/main/java/fr/cgi/magneto/controller/CardController.java
> +            current = current.compose(v -> duplicateCard(boardId, boardPayload, card, user));
en gros en plus de les dupliquer on les rajoutes a un tableau d'id du côté des boards, du coup pas sur qu'écrire au meme endroit dans le model au meme moment soit cool !

2022-11-03 10:19 UTC, Sofianebernoussi commented on src/main/java/fr/cgi/magneto/controller/CardController.java
> +        return promise.future();
yep bien vu

2022-11-03 10:20 UTC, Sofianebernoussi commented on src/main/java/fr/cgi/magneto/controller/CardController.java
> +    }
j'ai pas le boardService dans mon service Card, je sais pas trop si c'est une bonne chose de l'inclure

2022-11-03 10:21 UTC, qpic-cgi commented on src/main/java/fr/cgi/magneto/controller/CardController.java
> +            current = current.compose(v -> duplicateCard(boardId, boardPayload, card, user));
Mmh, tu as tester ? car en soit tu ne fais qu'agrandir le tableau ! A mon sens, tu peux le faire en Asynchrone.

2022-11-03 10:22 UTC, qpic-cgi commented on src/main/java/fr/cgi/magneto/controller/CardController.java
> +    }
Pourquoi pas 😄 ?

2022-11-03 10:28 UTC, Sofianebernoussi commented on src/main/resources/public/ts/directives/card-collection/card-collection.directive.ts
> +            vm.submitDuplicate = async (card?: Card): Promise<void> => {
pour récupérer le onSubmit du parent via parse

2022-11-03 10:30 UTC, qpic-cgi commented on src/main/resources/public/ts/directives/card-collection/card-collection.directive.ts
> +            vm.submitDuplicate = async (card?: Card): Promise<void> => {
ça marche

2022-11-03 10:36 UTC, Sofianebernoussi commented on src/main/java/fr/cgi/magneto/controller/CardController.java
> +            current = current.compose(v -> duplicateCard(boardId, boardPayload, card, user));
j'avais testé avec ancienne version de cette fonction je vais retry je te dis

2022-11-03 10:39 UTC, Sofianebernoussi commented on src/main/resources/public/ts/directives/infinite-scroll.directive.ts
> +            });
c'est a dire?

2022-11-03 10:46 UTC, qpic-cgi commented on src/main/resources/public/ts/directives/infinite-scroll.directive.ts
> +            });
```suggestion
$(document).ready(function () {
    setScrollEvent(
        !!vm.querySelector ? $(angular.element(document.querySelector(vm.querySelector))) : $(window)
    );
});
            
private setScrollEvent (elem: ElemType): void { // nom de méthode à redéfinir
    elem.on("scroll", async () => {
        await vm.scroll();
    });
}
```

2022-11-03 10:48 UTC, Sofianebernoussi commented on src/main/resources/public/ts/directives/infinite-scroll.directive.ts
> +            });
ah oui ok pas mal du tout j'avais pas du tout compris ça merci beaucoup !!

2022-11-03 10:57 UTC, qpic-cgi commented on src/main/resources/public/ts/directives/infinite-scroll.directive.ts
> +            });
Avec plaisir ☺️

2022-11-03 13:23 UTC, BastienBenard commented on src/main/java/fr/cgi/magneto/service/impl/DefaultCardService.java
> +    public Future<JsonObject> updateBoard(BoardPayload board) {
Pourquoi ne pas mettre ces deux méthode dans l'interface ?

2022-11-03 13:24 UTC, BastienBenard commented on src/main/java/fr/cgi/magneto/service/impl/DefaultCardService.java
> +        BoardPayload boardPayload = new BoardPayload(boardResult.get(0).toJson());
Pas besoin de vérif si boardResult est vide ? Pourquoi passer une liste de board si tu n'utilise que le premier élément ? Autant fournir directement le Board non ?

2022-11-03 13:31 UTC, BastienBenard commented on src/main/java/fr/cgi/magneto/service/impl/DefaultCardService.java
> +        this.create(cardPayload, newId)
Pourquoi est ce que tu set l'id a null et pas a newId ?

2022-11-03 13:34 UTC, BastienBenard commented on src/main/resources/jsonschema/cardDuplicate.json
> +        ]
```
      "items": {
        "type": "string"
      }
```

2022-11-03 13:45 UTC, Sofianebernoussi commented on src/main/java/fr/cgi/magneto/service/impl/DefaultCardService.java
> +        this.create(cardPayload, newId)
a cause du constructeur qui permet l'update, il faut le mettre apres coup

2022-11-03 14:30 UTC, merged