feat(section): #MAG-103 add sections feature (front)
CGI-OPEN-ENT-NG/magneto pull request #56
Opened 2023-01-19 15:15 UTC by Sofianebernoussi

## Describe your changes

## Checklist tests

## Issue ticket number and link

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-01-20 08:18 UTC, c4role commented on src/main/resources/i18n/de.json
> +  "magneto.create.section.confirm": "La section a été crée avec succès.",
Il me semble que le féminin du participe passé du verbe "créer" s'écrit de cette manière : créée (au masculin 'créé')

2023-01-20 08:19 UTC, c4role commented on src/main/resources/i18n/en.json
> +  "magneto.create.section.confirm": "La section a été crée avec succès.",
cf commentaire précédent

2023-01-20 08:20 UTC, c4role commented on src/main/resources/i18n/es.json
> +  "magneto.create.section.confirm": "La section a été crée avec succès.",
idem

2023-01-20 08:21 UTC, c4role commented on src/main/resources/i18n/fr.json
> +  "magneto.create.section.confirm": "La section a été crée avec succès.",
idem

2023-01-20 08:22 UTC, c4role commented on src/main/resources/i18n/it.json
> +  "magneto.create.section.confirm": "La section a été crée avec succès.",
idem

2023-01-20 08:23 UTC, c4role commented on src/main/resources/i18n/pt.json
> +  "magneto.create.section.confirm": "La section a été crée avec succès.",
idem

2023-01-20 08:32 UTC, c4role approved these changes
Juste l'orthographe du i18n, je l'ai mis dans chaque fichier mais en fait tu peux seulement le changer dans le fr je pense étant donné que de toute façon les autres devront être traduit.

2023-01-20 09:09 UTC, qpic-cgi requested changes

2023-01-20 09:09 UTC, qpic-cgi commented on src/main/resources/public/ts/controllers/board-view.controller.ts
> +        await Promise.all(requests);
getCardsBySectionBoard = async (): Promise<void> => Promise.all(this.board.sections.map((section) => this.getCardsBySection(section)));

2023-01-20 09:09 UTC, qpic-cgi commented on src/main/resources/public/ts/directives/section-delete-lightbox/section-delete-lightbox.directive.ts
> +    onSubmit?;
tu ne type pas ça ?

2023-01-20 09:09 UTC, qpic-cgi commented on src/main/resources/public/ts/directives/section-list/section-list-item.directive.ts
> +    onMove?;
tu ne type pas tout ça ?

2023-01-20 09:09 UTC, qpic-cgi commented on src/main/resources/public/ts/directives/section-list/section-list.directive.ts
> +    onSubmit?;
type ?

2023-01-20 09:09 UTC, qpic-cgi commented on src/main/resources/public/ts/directives/section-list/section-list.directive.ts
> +}
J'ai remarqué que la section-list et la section-list-item ont beaucoup de méthodes en commun.
Il n'y aurait pas moyen de faire un peu de générique sur ce qui est possible ? ou c'es trop relou à faire ?

2023-01-20 10:12 UTC, aymericdevriesere commented on src/main/resources/public/ts/directives/section-list/section-list.directive.ts
> +        await sectionsService.create(section).then(response => {
peut-être un try catch en cas de probleme sur le call ?

2023-01-23 09:09 UTC, flmartineau approved these changes

2023-01-23 09:20 UTC, qpic-cgi approved these changes

2023-01-23 09:22 UTC, merged